# Generated by Django 3.2.4 on 2021-07-01 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floris', '0002_auto_20210622_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='floris.user'),
        ),
        migrations.DeleteModel(
            name='Flowers',
        ),
    ]
