# Generated by Django 3.2.4 on 2021-07-01 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('floris', '0003_auto_20210701_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='owner_id',
        ),
        migrations.AddField(
            model_name='flower',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
